package dev.loam.spike

import org.json.JSONArray
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Before
import org.junit.Test
import java.io.File

/**
 * Differential test: our hand-rolled WordPiece against HuggingFace's reference.
 *
 * Fixtures in `tokenizer_fixtures.json` are generated by the real `tokenizers`
 * library from the same `tokenizer.json` that ships with the model — see
 * `scratchpad/gen_fixtures.py` in the commit that added this.
 *
 * This exists because a wrong tokenizer fails silently: it returns confident,
 * plausible embeddings that simply retrieve badly. Only a comparison against a
 * reference catches that.
 */
class WordPieceTokenizerTest {

    private lateinit var tokenizer: WordPieceTokenizer
    private lateinit var fixtures: JSONArray

    // Unit tests run with the module dir as working dir, so reach up to the
    // downloaded model rather than duplicating a 227KB vocab into the repo.
    private val vocabFile = File("../../models/all-MiniLM-L6-v2/vocab.txt")

    @Before
    fun setUp() {
        assumeTrue(
            "vocab.txt not found at ${vocabFile.absolutePath} — " +
                "download the model per the roadmap prerequisites",
            vocabFile.exists(),
        )
        tokenizer = WordPieceTokenizer(vocabFile)
        fixtures = JSONArray(
            javaClass.getResourceAsStream("/tokenizer_fixtures.json")!!
                .bufferedReader().readText()
        )
    }

    @Test
    fun matchesReferenceImplementation() {
        val failures = mutableListOf<String>()

        for (i in 0 until fixtures.length()) {
            val case = fixtures.getJSONObject(i)
            val text = case.getString("text")
            val expectedIds = case.getJSONArray("ids").let { arr ->
                LongArray(arr.length()) { arr.getLong(it) }
            }

            // Compare only the real tokens; our encode() pads to maxLen.
            val encoded = tokenizer.encode(text, maxLen = 512)
            val actualIds = encoded.inputIds
                .zip(encoded.attentionMask.toTypedArray())
                .filter { it.second == 1L }
                .map { it.first }
                .toLongArray()

            if (!expectedIds.contentEquals(actualIds)) {
                failures += buildString {
                    appendLine("  input:    ${text.take(60).replace("\n", "\\n")}")
                    appendLine("    expected: ${expectedIds.toList()}")
                    appendLine("    actual:   ${actualIds.toList()}")
                }
            }
        }

        assertTrue(
            "Tokenizer diverges from HuggingFace on ${failures.size}/${fixtures.length()} cases:\n" +
                failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    @Test
    fun padsAndMasksConsistently() {
        val enc = tokenizer.encode("hello world", maxLen = 16)
        assertEquals(16, enc.inputIds.size)
        assertEquals(16, enc.attentionMask.size)
        assertEquals(16, enc.tokenTypeIds.size)

        val realTokens = enc.attentionMask.count { it == 1L }
        assertEquals("[CLS] hello world [SEP]", 4, realTokens)
        // Padding must be masked out, or mean pooling silently averages in [PAD].
        for (i in realTokens until 16) {
            assertEquals("padding not masked at $i", 0L, enc.attentionMask[i])
            assertEquals("padding id not zero at $i", 0L, enc.inputIds[i])
        }
    }

    @Test
    fun truncatesToMaxLenWithSepIntact() {
        val long = List(200) { "word$it" }.joinToString(" ")
        val enc = tokenizer.encode(long, maxLen = 32)
        assertEquals(32, enc.inputIds.size)
        assertEquals("all slots should be real tokens", 32, enc.attentionMask.count { it == 1L })
    }
}
