package dev.loam.core.store

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Supplies the SQLCipher passphrase, held under a hardware-backed key.
 *
 * The index is derived from personal notes, so it is roughly as sensitive as
 * the notes themselves — chunk text is stored verbatim. Encrypting it is a
 * stated principle, not polish.
 *
 * How it works: a 32-byte random passphrase is generated once and sealed with
 * an AES-GCM key that lives in the Android Keystore and cannot be exported.
 * Only the sealed bytes touch shared preferences. Extracting the passphrase off
 * a locked device therefore means defeating the Keystore, not reading a file.
 *
 * Deliberately not using Jetpack Security's EncryptedSharedPreferences: this is
 * ~40 lines of visible cryptography versus a dependency, and Core principle #4
 * asks for auditable over convenient.
 *
 * Phase 3 layers BiometricPrompt on top by requiring user authentication on the
 * Keystore key. That is a spec change on the key, not a re-encryption, so it
 * costs no migration.
 */
object DatabaseKey {

    private const val PREFS = "loam_key_store"
    private const val PREF_SEALED = "sealed_passphrase"
    private const val KEY_ALIAS = "loam_db_key"
    private const val KEYSTORE = "AndroidKeyStore"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_BITS = 128
    private const val GCM_IV_BYTES = 12
    private const val PASSPHRASE_BYTES = 32

    @Synchronized
    fun getOrCreate(context: Context): ByteArray {
        val prefs = context.applicationContext
            .getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        prefs.getString(PREF_SEALED, null)?.let { return unseal(it) }

        val passphrase = ByteArray(PASSPHRASE_BYTES).also {
            java.security.SecureRandom().nextBytes(it)
        }
        prefs.edit().putString(PREF_SEALED, seal(passphrase)).commit()
        return passphrase
    }

    /** Drops the key, making any existing database permanently unreadable. */
    @Synchronized
    fun clear(context: Context) {
        context.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit().remove(PREF_SEALED).commit()
        keyStore().deleteEntry(KEY_ALIAS)
    }

    private fun seal(plaintext: ByteArray): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val encrypted = cipher.doFinal(plaintext)
        // IV is generated by the cipher and must be stored with the ciphertext;
        // it is not secret, only single-use.
        return Base64.encodeToString(cipher.iv + encrypted, Base64.NO_WRAP)
    }

    private fun unseal(sealed: String): ByteArray {
        val bytes = Base64.decode(sealed, Base64.NO_WRAP)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(GCM_TAG_BITS, bytes, 0, GCM_IV_BYTES),
        )
        return cipher.doFinal(bytes, GCM_IV_BYTES, bytes.size - GCM_IV_BYTES)
    }

    private fun keyStore(): KeyStore = KeyStore.getInstance(KEYSTORE).apply { load(null) }

    private fun secretKey(): SecretKey {
        val existing = keyStore().getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
        if (existing != null) return existing.secretKey

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }
}
